### ISSUE TITLE
parse float error

### ISSUE THREAD

**Issue by anranyicheng** [yitzchak/shasht#10]
Hi, there is a mistake:
`(read-json  "[9999.123412198234711873809123847189023748192370418230841273480917238417039480173480197234324018973041732081237408917230984712389074108329471892347123249740123748120374192837409127398041723089471980237489012374089127389041720389471098234710283947984172038947109283471098374810273401728034701928343412341123441234123413412341234]" `

**Comment by yitzchak** [comment]
Floating point numbers do not have infinite precision. You need to pick a float format. Its discussed briefly here https://github.com/yitzchak/shasht#reading

**Comment by anranyicheng** [comment]
but this is also:
 (read-json* :stream "[9999.1234121982347118738091238471890237481923704182308412734809172384170394801734801972343240189730417320984172038947109283471098374810273401728034701928343412341123441234123413412341234182734098172389412730984172389471209387410928374189023741982037410982374910237410293471902374918023490172389412093471902837410289347189237409123741928034719802347]" 
					:float-format 'double-float )
