### ISSUE TITLE
Empty list (NIL) recognized as `false` despite settings

### ISSUE THREAD

**Issue by sheepduke** [yitzchak/shasht#13]
I truly love this project. :-)

Just found a potential bug that output settings are not respected. The following code (and output) should be reproducible in `shasht-20220707`.

```lisp
(defclass my-class ()
  ((name :initarg :name)
   (value-list :initarg :value-list)))

(let ((obj (make-instance 'my-class
                          :name "Name"
                          :value-list nil))
      (cl:*print-pretty* nil)
      (shasht:*write-false-values* '(:false))
      (shasht:*write-empty-array-values* '(:empty-array nil)))
  (shasht:write-json obj nil)) ; => "{\"NAME\":\"Name\",\"VALUE-LIST\":false}"
```

Expected result: `"{\"NAME\":\"Name\",\"VALUE-LIST\":[]}"`

**Comment by yitzchak** [comment]
shasht uses the `:type` of each slot in order to determine what to do with nil. Specifically here: https://github.com/yitzchak/shasht/blob/1f4f063b75a77c95eabcd6a41e18e4246cf87881/src/write.lisp#L249-L274

In order to print nil as an empty list for that slot you need to add `:type list` to the slot definition.

```lisp
(defclass my-class ()
  ((name :initarg :name)
   (value-list :initarg :value-list
               :type list)))

(let ((obj (make-instance 'my-class
                          :name "Name"
                          :value-list nil))
      (cl:*print-pretty* nil)
      (shasht:*write-false-values* '(:false))
      (shasht:*write-empty-array-values* '(:empty-array nil)))
  (shasht:write-json obj nil)) ; => "{\"NAME\":\"Name\",\"VALUE-LIST\":false}"
; => "{\"NAME\":\"Name\",\"VALUE-LIST\":[]}"
```

**Comment by sheepduke** [comment]
I added `:type` to the `defclass` form and it did work. 

I appreciate this design and I think it is very logical, but it is a bit confusing because whether slot types are being checked or not is undefined in CL spec. I mean, some people may not have the habit to always add a `:type` property to a slot. 

I suggest that you explicitly mention this in the docs to make it more obvious :-)
