### ISSUE TITLE
Lower-casing in JSON output from lisp structs

### ISSUE THREAD

**Issue by nathanvy** [yitzchak/shasht#18]
Consider the following snippet:

```
CL-USER> (defstruct test-struct payload)
TEST-STRUCT
CL-USER> (let ((s (make-test-struct))) 
  (setf (test-struct-payload s) "fgsfds") 
  (shasht:write-json s nil))
"{
  \"PAYLOAD\": \"fgsfds\"
}"
```

My frontend expects the JSON to have lower-case keys.  In other words it is expecting `"payload": "fgsfds"` and not `"PAYLOAD": "fgsfds"`.  How can I achieve lower-case key names in the emitted JSON string?  I'm not married to using structs on the backend if there's an easier way that is performant.

**Comment by yitzchak** [comment]
Use `*symbol-name-function*`. Its not documented because I haven't decided if there should be a generic interface.

```
CL-USER> (defstruct test-struct payload)

TEST-STRUCT
CL-USER> (let ((s (make-test-struct))
               (shasht:*symbol-name-function* (lambda (sym) 
                                                (string-downcase (symbol-name sym)))))
           (setf (test-struct-payload s) "fgsfds") 
           (shasht:write-json s nil))
"{
  \"payload\": \"fgsfds\"
}"
CL-USER> 
```

**Comment by nathanvy** [comment]
Awesome, thank you.
