### ISSUE TITLE
write-json* :NULL-VALUES is not a known argument keyword.

### ISSUE THREAD

**Issue by qubit55** [yitzchak/shasht#19]
Hello, 

I think there's a mismatch between the docs and the function arguments of the write-json* function. This [argument](https://github.com/yitzchak/shasht/blob/27ba0a8842e103f2d575b3c8bbcfc19bd172d9ea/src/write.lisp#L333C3-L333C14) is not present in the function's signature.

**Comment by yitzchak** [comment]
Pushed a fix

**Comment by qubit55** [comment]
Awesome, thanks!
