### ISSUE TITLE
Suggestion: make input/output selections with keywords

### ISSUE THREAD

**Issue by Symbolics** [yitzchak/shasht#3]
Input and output format are currently specified with special variables. It would be convenient if these were part of the `read-json` and `write-json` function arguments as keywords. E.g. `(read-json ... :format :alist)`, or something along those lines.

**Comment by yitzchak** [comment]
I was trying to emulate Lisp's own `read` and make the function signature as close as possible. What about adding a variant (`read-json*` or something) that takes keywords and sets the appropriate dynamic variables?

**Comment by Symbolics** [comment]
It's a good sentiment. When I think about `read` though, I think of something processed by the lisp reader, and `read-json` more like `read-line` or `uiop:read-file-lines`, neither of which interpret the input as anything other than a string.

You could also make `*read-default-object-format*` and friends the default for the keyword arguments, so they'd be optional in the hashtable case.

**Comment by yitzchak** [comment]
I think that I am going to make a variant that has keywords with specific defaults versus using dynamic variables as defaults. Doing the former could lead to subtle bugs if a subfunction makes assumptions about the values of the those variables. I am using dynamic variables in various places in the read algorithm and don't really want to pass the reader configuration around as a function argument.

**Comment by yitzchak** [comment]
PR #4 should address this. The `read-json*` and `write-json*` variants should have keywords for all the various configuration options. 

I'm adding some CI testing and cleaning up some other stuff in the PR. The read/write variants are at the end of `read.lisp` and `write.lisp`. Let me know if they will work for you.

**Comment by yitzchak** [comment]
Resolved by #4. I'll reopen if there are issues.
