### ISSUE TITLE
is :null really should be output as "null2" (rather than "null")?

### ISSUE THREAD

**Issue by Yehouda** [yitzchak/shasht#5]
in src/test/write.lisp there is:
````
(define-write-test "Write :null as null"
  :null
  "null2")
````
Is that correct? does it really want to  outptu :null as "null2" (rather than "null")? 
For me it output "null" and the test fail. 

It was changed in the add make-object" change:
https://github.com/yitzchak/shasht/commit/4055327ef8e2aaa8627892ab256350ff3cb15e3c

**Comment by yitzchak** [comment]
Fixed. Thanks again for reporting.
