### ISSUE TITLE
How do I read a multiline file in to a single hash-table?

### ISSUE THREAD

**Issue by patrickmay** [yitzchak/shasht#9]
I have a file with multiple lines of JSON that I'd like to read into the same hash-table.  By default, it looks like shasht reads only the first line:

```
(defparameter *twarc-data*
  (with-open-file (in +tweet-file+ :direction :input)
    (shasht:read-json in nil 'eof)))
```

**Comment by yitzchak** [comment]
The JSON spec does not permit multiple JSON expressions in the same file, much less merging objects into a single object. That said shasht does not enforce this requirement unless `single-value` is non-`NIL`. In other words you can call `read-json` multiple times, but you will have to merge the hash tables yourself.

```lisp
(with-open-file (in +tweet-file+ :direction :input)
  (loop for expr = (shasht:read-json in nil in)
        until (eq expr in)
        do (your-merge-stuff-here)))
```

**Comment by patrickmay** [comment]
Thank you, that makes sense.
